replicaCount: 1
image:
  repository: ghcr.io/intersectmbo/govtool-metadata-validation-dev
  tag: 6f0b1dc530615cd284d76c052616cfd32d4986dd-114

env:
  name: PORT
  value: 3000
  hostname: HOST
  host: 0.0.0.0

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
service:
  port: 80
  targetPort: 3000
strategy:
  maxSurge: "25%"
  maxUnavailable: "0"

fullnameOverride: "gt-metadata"