replicaCount: 1
image:
  repository: ghcr.io/aaboyle878/govtool-govtool-metadata-validation
  tag: develop-a38ed7fc73a15cbd4fb01b540b7833875233dd19

env:
  name: PORT
  value: 3000
  hostname: HOST
  host: 0.0.0.0

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

strategy:
  maxSurge: "25%"
  maxUnavailable: "0"

fullnameOverride: "gt-metadata"
service:
  name: "gt-metadata-service"
  port: 80
  targetPort: 3000
ingress:
  enabled: true
  className: nginx
  host: md.localhost
  tls:
    enabled: true
    secretName: md-tls
  clusterIssuer: cluster-issuer