replicaCount: 1

image:
  repository: ghcr.io/aaboyle878/govtool-govtool-backend
  tag: develop-a38ed7fc73a15cbd4fb01b540b7833875233dd19
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

strategy:
  maxSurge: "25%"
  maxUnavailable: "0"

secret:
  name: db-config
  create: false
  configJson: |
    {
      "dbsyncconfig" : {
        "host"    : "",
        "dbname"  : "",
        "user"    : "",
        "password" : "",
        "port"    : 5432
      },
      "port" : 9876,
      "host" : "0.0.0.0",
      "cachedurationseconds": 20,
      "sentrydsn": "",
      "sentryenv": ""
    }

fullnameOverride: "gt-backend"

service:
  name: "gt-backend-service"
  type: ClusterIP
  port: 80
  targetPort: 9876

ingress:
  enabled: true
  className: nginx
  host: be.localhost
  tls:
    enabled: true
    secretName: be-tls
  clusterIssuer: cluster-issuer