replicaCount: 1

image:
  repository: ghcr.io/intersectmbo/govtool-backend-prod
  tag: 8423e2c39d14d52acf9e35a9427ece0b1d62b755-118
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

strategy:
  maxSurge: "25%"
  maxUnavailable: "0"

service:
  type: ClusterIP
  port: 80
  targetPort: 9876

secret:
  name: db-config
  create: true
  configJson: |
    {
      "dbsyncconfig" : {
        "host"    : "dbsync-v3.demeter.run",
        "dbname"  : "",
        "user"    : "",
        "password" : "",
        "port"    : 5432
      },
      "port" : 9876,
      "host" : "0.0.0.0",
      "cachedurationseconds": 20,
      "sentrydsn": "",
      "sentryenv": ""
    }

fullnameOverride: "gt-backend"